name: Deploy to alternate-wm-selector.github.io
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Checkout private tools
        uses: actions/checkout@v3
        with:
          repository: noresjo/alternate-wm-selector.github.io
          token: ${{ secrets.DEPLOY_KEY }}
          path: pages-repo
      
      - uses: actions/setup-node@v2
      - name: Build and Deploy
        run: |
          npm ci
          npm run build
          rm -Rf pages-repo/*
          cp -Rf dist/* pages-repo/
          cd pages-repo/
          git config user.email 'bot@botmail.com'
          git config user.name 'Bot Automatica'
          git checkout README.md
          git add .
          git commit -m '${{ github.repository }} ${{ github.sha }}'
          git push -f origin main
